const TMP_PATH = '/tmp/'
const CLASSIFIER_FILE_NAME = 'haarcascade_frontalface_alt.xml'
const HOME_ASSISTANT_FOLDER_PATH = `${TMP_PATH}home-assistant/`
const HOME_ASSISTANT_TRAINER_IMGS_FOLDER_PATH = `${HOME_ASSISTANT_FOLDER_PATH}trainer-img/`
const HOME_ASSISTANT_CLASSIFIER_PATH = `${HOME_ASSISTANT_FOLDER_PATH}${CLASSIFIER_FILE_NAME}`

const ERROR_MUTLI_SCALE_DETECTION = 'Failed to detect faces'

export {
  HOME_ASSISTANT_FOLDER_PATH,
  HOME_ASSISTANT_TRAINER_IMGS_FOLDER_PATH,
  HOME_ASSISTANT_CLASSIFIER_PATH,
  ERROR_MUTLI_SCALE_DETECTION,
  CLASSIFIER_FILE_NAME
}
