const SET_INTERVAL = 'SET INTERVAL'
const SET_CURRENT_FRAME = 'SET CURRENT FRAME'
const SET_LOAD_IMAGES_SAMPLE = 'SET LOAD IMAGES SAMPLE'
const SET_IMAGES_SAMPLE = 'SET IMAGES SAMPLE'
const PUSH_IMAGE_TO_IMAGES_SAMPLE = 'PUSH IMAGE TO IMAGES SAMPLE'

export {
  SET_INTERVAL,
  SET_CURRENT_FRAME,
  SET_LOAD_IMAGES_SAMPLE,
  SET_IMAGES_SAMPLE,
  PUSH_IMAGE_TO_IMAGES_SAMPLE
}
